# Generated by Django 5.2.6 on 2025-09-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tower',
            name='bells',
            field=models.IntegerField(help_text='Number of ringable bells', null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week of main practice', max_length=9),
        ),
        migrations.AlterField(
            model_name='tower',
            name='dove_ring_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='dove_tower_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tower',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tower',
            name='long_Notes',
            field=models.TextField(blank=True, help_text='For display when space isn’t at a premium'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='maintainer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='note',
            field=models.CharField(blank=True, help_text='Use ‘b’ and ‘#’', max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='notes',
            field=models.CharField(blank=True, help_text='For display, especially in the Annual Report', max_length=100),
        ),
        migrations.AlterField(
            model_name='tower',
            name='os_grid',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tower',
            name='peals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='practice',
            field=models.CharField(blank=True, help_text='Short description of normal practice ringing. No initial capital (unless day of week)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tower',
            name='service',
            field=models.CharField(blank=True, help_text='Short description of normal service ringing. No initial capital (unless day of week)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tower',
            name='towerbase_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='week',
            field=models.CharField(blank=True, help_text="Week(s) of the month for main practice if not all [‘2nd, 5th’, 'alt']", max_length=50),
        ),
        migrations.AlterField(
            model_name='tower',
            name='weight',
            field=models.CharField(blank=True, help_text='‘15-3-13’, ‘6cwt’', max_length=50),
        ),
    ]
