# Generated by Django 5.2.6 on 2025-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_entity_name_alter_tower_bells_alter_tower_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tower',
            old_name='long_Notes',
            new_name='long_notes',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='dove_ring_id',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='dove_tower_id',
        ),
        migrations.AddField(
            model_name='tower',
            name='dove_ringid',
            field=models.CharField(blank=True, max_length=10, verbose_name='Dove RingID'),
        ),
        migrations.AddField(
            model_name='tower',
            name='dove_towerid',
            field=models.CharField(blank=True, max_length=10, verbose_name='Dove TowerID'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='county',
            field=models.CharField(choices=[('C', 'Cambridgeshire'), ('N', 'Norfolk')], default='Cambridgeshire', max_length=100),
        ),
        migrations.AlterField(
            model_name='tower',
            name='os_grid',
            field=models.CharField(blank=True, max_length=8, verbose_name='OS Grid'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='towerbase_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Towerbase ID'),
        ),
    ]
