# Generated by Django 5.2.6 on 2025-09-18 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_long_notes_tower_long_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='bells',
            field=models.IntegerField(blank=True, help_text='Number of ringable bells', null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='peals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_primary_set', to='database.entity'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='ring_type',
            field=models.CharField(blank=True, choices=[('Full-circle', 'Full-circle ring'), ('Lightweight', 'Lightweight ring'), ('Carillon', 'Carillon'), ('C-Chine', 'Clock chime'), ('T-Chime', 'Tubular chime'), ('H-Chinme', 'Hemispherical chime'), ('Chime', 'Chime'), ('Display', 'Display bells'), ('Future', 'Future ring'), ('Other', 'Other bells')], max_length=20, null=True),
        ),
    ]
