# Generated by Django 5.2.6 on 2025-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_tower_bells_alter_tower_peals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
