# Generated by Django 5.2.6 on 2025-09-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_tower_lat_alter_tower_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmeans',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.contact'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_primary_set', to='database.contact'),
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ContactMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TCor', 'Tower Corespondent'), ('TC', 'Tower Captain'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.contact')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tower')),
            ],
            options={
                'ordering': ['tower', 'role'],
                'unique_together': {('tower', 'entity')},
            },
        ),
        migrations.AlterField(
            model_name='tower',
            name='other_contacts',
            field=models.ManyToManyField(related_name='tower_oher_set', through='database.ContactMap', to='database.contact'),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='role',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tower',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
