# Generated by Django 5.2.6 on 2025-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_contactmeans_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='contact_restrictions',
            field=models.CharField(blank=True, choices=[('Bells only', 'Bells only'), ('Band only', 'Band only')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contactmap',
            name='role',
            field=models.CharField(choices=[('Contact', 'Other contact'), ('Tower Captain', 'Tower Captain'), ('Ringing Master', 'Ringing Master'), ('Steeplekeeper', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tower',
            name='gf',
            field=models.BooleanField(blank=True, help_text='Ground Floor?', null=True),
        ),
    ]
