# Generated by Django 5.2.6 on 2025-09-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_tower_contact_restrictions_alter_contactmap_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmeans',
            old_name='entity',
            new_name='contact',
        ),
    ]
