# Generated by Django 5.2.6 on 2025-09-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_entity_contactmeans_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMeans',
            new_name='ContactMethod',
        ),
    ]
