# Generated by Django 5.2.6 on 2025-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_contactmeans_contactmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='contact_restrictions',
            field=models.CharField(choices=[('None', 'None'), ('Bells only', 'Bells only'), ('Band only', 'Band only')], default='None', max_length=10),
        ),
    ]
