# Generated by Django 5.2.6 on 2025-09-19 10:08

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_tower_contact_restrictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmap',
            old_name='entity',
            new_name='contact',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='contact_type',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Other', 'Other')], max_length=5),
        ),
        migrations.AlterField(
            model_name='tower',
            name='bells',
            field=models.PositiveIntegerField(blank=True, help_text='Number of ringable bells', null=True, validators=[database.models.Tower.bell_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='check_before_traveling',
            field=models.BooleanField(default=False, help_text='Check before travelling to practices?'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week of main practice', max_length=9, verbose_name='Practoce day'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='dedication',
            field=models.CharField(help_text='Church dedication. Use ‘St’ not ‘St.’; ‘and’ not ‘&’', max_length=100),
        ),
        migrations.AlterField(
            model_name='tower',
            name='gf',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ground Floor?'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='note',
            field=models.CharField(blank=True, help_text='Use ‘b’ and ‘#’', max_length=10, validators=[database.models.Tower.note_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='os_grid',
            field=models.CharField(blank=True, max_length=8, validators=[database.models.Tower.grid_validator], verbose_name='OS Grid'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='peals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tower',
            name='place',
            field=models.CharField(help_text='Town or village containing the tower', max_length=100),
        ),
        migrations.AlterField(
            model_name='tower',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, validators=[database.models.Tower.postcode_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='practice',
            field=models.CharField(blank=True, help_text='Short description of normal practice ringing. No initial capital (unless day of week)', max_length=200, validators=[database.models.Tower.time_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='report',
            field=models.BooleanField(default=False, verbose_name='In annual report?'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='service',
            field=models.CharField(blank=True, help_text='Short description of normal service ringing. No initial capital (unless day of week)', max_length=200, validators=[database.models.Tower.time_validator]),
        ),
        migrations.AlterField(
            model_name='tower',
            name='weight',
            field=models.CharField(blank=True, help_text='Use ‘15-3-13’ or ‘6cwt’', max_length=50, validators=[database.models.Tower.weight_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='contactmap',
            unique_together={('tower', 'contact')},
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('contact_type', 'contact_value', 'contact'), name='unique_contact_type_value', violation_error_message='This contact method already exists for this contact'),
        ),
        migrations.AddConstraint(
            model_name='tower',
            constraint=models.UniqueConstraint(fields=('place', 'dedication'), name='unique_place_dedication', violation_error_message="Can't have two towers with the same place and dedication"),
        ),
    ]
