# Generated by Django 5.2.6 on 2025-09-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_entity_contactmap_contact_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactmap',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
