# Generated by Django 5.2.6 on 2025-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_contact_options_contact_email_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tower',
            name='contact_restrictions',
        ),
        migrations.AddField(
            model_name='tower',
            name='contact_use',
            field=models.CharField(choices=[('None', 'None'), ('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('All', 'All')], default='All', help_text='Intended use of contact details', max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week of main practice', max_length=9, verbose_name='Practice day'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='district',
            field=models.CharField(choices=[('C', 'Cambridgeshire'), ('E', 'Ely'), ('H', 'Huntingdon'), ('W', 'Wisbech')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tower',
            name='ring_type',
            field=models.CharField(blank=True, choices=[('Full', 'Full-circle ring'), ('Light', 'Lightweight ring'), ('Carillon', 'Carillon'), ('C-chine', 'Clock chime'), ('T-chime', 'Tubular chime'), ('H-chinme', 'Hemispherical chime'), ('Chime', 'Chime'), ('Display', 'Display bells'), ('Future', 'Future ring'), ('Other', 'Other bells')], max_length=20, null=True),
        ),
    ]
