# Generated by Django 5.2.6 on 2025-09-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_tower_contact_restrictions_tower_contact_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmap',
            name='role',
            field=models.CharField(choices=[('C', 'Other Contact'), ('TC', 'Tower Captai'), ('RM', 'Ringing Master'), ('SK', 'Steeplekeeper')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tower',
            name='contact_use',
            field=models.CharField(choices=[('All', 'All'), ('Bells only', 'Bells Only'), ('Band only', 'Band Only'), ('None', 'None')], default='All', help_text='Intended use of contact details', max_length=10),
        ),
    ]
