# Generated by Django 5.2.6 on 2025-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_contactmap_role_alter_tower_contact_use'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tower',
            name='website',
        ),
        migrations.AlterField(
            model_name='tower',
            name='day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week of main practice', max_length=9, verbose_name='Practice day'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='district',
            field=models.CharField(choices=[('C', 'Cambridge'), ('E', 'Ely'), ('H', 'Huntingdon'), ('W', 'Wisbech')], max_length=10),
        ),
    ]
