# Generated by Django 5.2.6 on 2025-09-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_website_remove_tower_website_alter_tower_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
