# Generated by Django 5.2.6 on 2025-09-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_delete_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.tower')),
            ],
        ),
    ]
