# Generated by Django 5.2.6 on 2025-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['website']},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name', 'phone', 'phone2', 'email')},
        ),
        migrations.AddField(
            model_name='contactmap',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='publish',
        ),
    ]
