# Generated by Django 5.2.6 on 2025-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_alter_website_options_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('name', ''), _negated=True), models.Q(('phone', ''), _negated=True), models.Q(('phone2', ''), _negated=True), models.Q(('email', ''), _negated=True), _connector='OR'), name='no_non_blank_contacts', violation_error_message="Contacts can't be entirely blank"),
        ),
    ]
