# Generated by Django 5.2.6 on 2025-09-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_contact_no_non_blank_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tower',
            old_name='week',
            new_name='practice_weeks',
        ),
        migrations.RenameField(
            model_name='tower',
            old_name='check_before_traveling',
            new_name='travel_check',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tower',
            name='ringing',
        ),
        migrations.AddField(
            model_name='tower',
            name='practice_day',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], help_text='Day of the week of main practice', max_length=9),
        ),
        migrations.AddField(
            model_name='tower',
            name='ringing_status',
            field=models.CharField(blank=True, choices=[('R', 'Regular'), ('O', 'Occasional'), ('N', 'None')], help_text='Full-circle ringing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='tower',
            name='include_dedication',
            field=models.BooleanField(default=False, help_text='For places with more than one tower [Cambridge], or for towers in different places that have the same name [Chesterton])'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='primary_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tower_primary_set', to='database.contact'),
        ),
        migrations.AlterField(
            model_name='tower',
            name='ring_type',
            field=models.CharField(blank=True, choices=[('Full', 'Full-circle ring'), ('Light', 'Lightweight ring'), ('Carillon', 'Carillon'), ('C-chine', 'Clock chime'), ('T-chime', 'Tubular chime'), ('H-chinme', 'Hemispherical chime'), ('Chime', 'Chime'), ('Display', 'Display bells'), ('Future', 'Future ring'), ('Other', 'Other bells')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
